language: node_js
dist: precise
node_js:
- 7
branches:
    only:
    - source
before_script:
- npm install -g grunt
- npm install -g handlebars-helpers
script: grunt
after_success:
- bash ./deploy.sh
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
env:
    global:
    - ENCRYPTION_LABEL: "2ed699ca3770"
    - COMMIT_AUTHOR_EMAIL: "MCResourcePile@gmail.com"
